apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: kubedemo
    tier: frontend
spec:
  selector:
    app: kubedemo
    tier: frontend
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: kubedemo
    tier: frontend
